version: '3'
services:
  hasura:
    image: hasura/graphql-engine:v2.16.0.cli-migrations-v3
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgres@postgres:5432/hasura_metadata
      HASURA_GRAPHQL_CRM_DATABASE_URL: postgres://postgres:postgres@postgres:5432/crm
      HASURA_GRAPHQL_MAIN_DATABASE_URL: postgres://postgres:postgres@postgres:5432/main
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: secret
    depends_on:
      - postgres
      - api
    restart: always
    working_dir: /app
    volumes:
      - ./gdg-sample-hasura:/app
      - ./gdg-sample-hasura/migrations:/hasura-migrations
      - ./gdg-sample-hasura/metadata:/hasura-metadata
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/db_data:/var/lib/postgresql/data
  
  api:
    image: node:14
    volumes:
      - ./gdg-sample-api:/app
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./data/pgadmin_data:/var/lib/pgadmin

