table:
  name: users
  schema: public
remote_relationships:
  - definition:
      to_source:
        field_mapping:
          id: user_id
        relationship_type: array
        source: main
        table:
          name: baskets
          schema: public
    name: users_baskets
select_permissions:
  - role: user
    permission:
      columns:
        - id
        - email
      filter:
        id:
          _eq: X-Hasura-User-Id
event_triggers:
  - name: send_welcome_email
    definition:
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook_from_env: SEND_WELCOME_EMAIL_URL
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
