-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."baskets_products" add column "count" integer
--  not null default '1';
